[package]
name = "rust_python_variable_explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pyo3]
version = "0.18.0"
features = ["auto-initialize"]

[dependencies]
rocket = "0.5.0-rc.2"
